use crate::cpu::Mos6502;
pub type Opcode = (Mnemonic, AddressingMode);

#[repr(u8)]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum AddressingMode {
    Implied,     // e.g., CLC
    Accumulator, // e.g., ASL A
    Immediate,   // e.g., LDA #$01
    ZeroPage,    // e.g., LDA $00
    ZeroPageX,   // e.g., LDA $00,X
    ZeroPageY,   // e.g., LDX $00,Y (only some instructions use Y here)
    Relative,    // e.g., BNE label
    Absolute,    // e.g., JMP $1234
    AbsoluteX,   // e.g., LDA $1234,X
    AbsoluteY,   // e.g., LDA $1234,Y
    Indirect,    // JMP ($1234)
    IndirectX,   // LDA ($20,X)
    IndirectY,   // LDA ($20),Y
}

impl AddressingMode {
    pub fn get_bytes(self) -> u8 {
        use AddressingMode::*;
        match self {
            Implied | Accumulator => 1,
            Immediate | ZeroPage | ZeroPageX | ZeroPageY | Relative | IndirectX | IndirectY => 2,
            Absolute | AbsoluteX | AbsoluteY | Indirect => 3,
        }
    }
    pub fn apply(self, cpu: &mut Mos6502) {
        use AddressingMode::*;
        match self {
            Implied => {}
            Accumulator => {
                cpu.fetched = cpu.a;
            }
            Immediate => {
                let operand = cpu.inc_pc();
                cpu.abs_addr = operand as u16;
                cpu.fetched = operand;
            }
            ZeroPage => {
                let zero_page_addr = cpu.inc_pc() as u16;
                cpu.abs_addr = zero_page_addr;
                cpu.fetched = cpu.bus.read(zero_page_addr);
            }
            ZeroPageX => {
                let zero_page_addr = cpu.inc_pc().wrapping_add(cpu.x) as u16;
                cpu.abs_addr = zero_page_addr as u16;
                cpu.fetched = cpu.bus.read(zero_page_addr);
            }
            ZeroPageY => {
                let zero_page_addr = cpu.inc_pc().wrapping_add(cpu.y) as u16;
                cpu.abs_addr = zero_page_addr as u16;
                cpu.fetched = cpu.bus.read(zero_page_addr);
            }
            Relative => {
                let value = cpu.inc_pc();
                cpu.fetched = value;
            }
            Absolute => {
                let lo = cpu.inc_pc();
                let hh: u8 = cpu.inc_pc();
                let addr = Mos6502::get_address_from_bytes(hh, lo);
                cpu.fetched = cpu.bus.read(addr);
                cpu.abs_addr = addr;
            }
            AbsoluteX => {
                let lo = cpu.inc_pc();
                let hh = cpu.inc_pc();
                let addr = Mos6502::get_address_from_bytes(hh, lo).wrapping_add(cpu.x as u16);
                cpu.fetched = cpu.bus.read(addr);
                cpu.abs_addr = addr;
            }
            AbsoluteY => {
                let lo = cpu.inc_pc();
                let hh = cpu.inc_pc();
                let addr = Mos6502::get_address_from_bytes(hh, lo).wrapping_add(cpu.y as u16);
                cpu.fetched = cpu.bus.read(addr);
                cpu.abs_addr = addr;
            }
            Indirect => {
                // 6502 JMP supports only absolute addressing (16-bit operand); no zero-page or immediate forms exist.
            }
            IndirectX => {
                let mut byte = cpu.inc_pc();
                byte = byte.wrapping_add(cpu.x);

                let lo = cpu.bus.read(byte as u16);
                let hi = cpu.bus.read((byte.wrapping_add(1)) as u16 & 0x00FF);
                cpu.abs_addr = Mos6502::get_address_from_bytes(hi, lo);
                cpu.fetched = cpu.bus.read(cpu.abs_addr);
            }
            IndirectY => {
                let addr = cpu.inc_pc() as u16;

                let lo = cpu.bus.read(addr as u16);
                let hi = cpu.bus.read((addr.wrapping_add(1)) as u16 & 0x00FF);
                cpu.abs_addr = Mos6502::get_address_from_bytes(hi, lo).wrapping_add(cpu.y as u16);
                cpu.fetched = cpu.bus.read(cpu.abs_addr);
            }
        }
    }
}
pub fn resolve_opcode(n: u8) -> Option<Opcode> {
    match n {
        0x00 => Some((Mnemonic::BRK, AddressingMode::Implied)),
        0x01 => Some((Mnemonic::ORA, AddressingMode::IndirectX)),
        0x02 => None,
        0x03 => Some((Mnemonic::SLO, AddressingMode::IndirectX)),
        0x04 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPage)),
        0x05 => Some((Mnemonic::ORA, AddressingMode::ZeroPage)),
        0x06 => Some((Mnemonic::ASL, AddressingMode::ZeroPage)),
        0x07 => Some((Mnemonic::SLO, AddressingMode::ZeroPage)),
        0x08 => Some((Mnemonic::PHP, AddressingMode::Implied)),
        0x09 => Some((Mnemonic::ORA, AddressingMode::Immediate)),
        0x0a => Some((Mnemonic::ASL, AddressingMode::Accumulator)),
        0x0b => None,
        0x0c => Some((Mnemonic::UndocumentedNOP, AddressingMode::Absolute)),
        0x0d => Some((Mnemonic::ORA, AddressingMode::Absolute)),
        0x0e => Some((Mnemonic::ASL, AddressingMode::Absolute)),
        0x0f => Some((Mnemonic::SLO, AddressingMode::Absolute)),
        0x10 => Some((Mnemonic::BPL, AddressingMode::Relative)),
        0x11 => Some((Mnemonic::ORA, AddressingMode::IndirectY)),
        0x12 => None,
        0x13 => Some((Mnemonic::SLO, AddressingMode::IndirectY)),
        0x14 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPageX)),
        0x15 => Some((Mnemonic::ORA, AddressingMode::ZeroPageX)),
        0x16 => Some((Mnemonic::ASL, AddressingMode::ZeroPageX)),
        0x17 => Some((Mnemonic::SLO, AddressingMode::ZeroPageX)),
        0x18 => Some((Mnemonic::CLC, AddressingMode::Implied)),
        0x19 => Some((Mnemonic::ORA, AddressingMode::AbsoluteY)),
        0x1a => Some((Mnemonic::UndocumentedNOP, AddressingMode::Implied)),
        0x1b => Some((Mnemonic::SLO, AddressingMode::AbsoluteY)),
        0x1c => Some((Mnemonic::UndocumentedNOP, AddressingMode::Absolute)),
        0x1d => Some((Mnemonic::ORA, AddressingMode::AbsoluteX)),
        0x1e => Some((Mnemonic::ASL, AddressingMode::AbsoluteX)),
        0x1f => Some((Mnemonic::SLO, AddressingMode::AbsoluteX)),
        0x20 => Some((Mnemonic::JSR, AddressingMode::Absolute)),
        0x21 => Some((Mnemonic::AND, AddressingMode::IndirectX)),
        0x22 => None,
        0x23 => Some((Mnemonic::RLA, AddressingMode::IndirectX)),
        0x24 => Some((Mnemonic::BIT, AddressingMode::ZeroPage)),
        0x25 => Some((Mnemonic::AND, AddressingMode::ZeroPage)),
        0x26 => Some((Mnemonic::ROL, AddressingMode::ZeroPage)),
        0x27 => Some((Mnemonic::RLA, AddressingMode::ZeroPage)),
        0x28 => Some((Mnemonic::PLP, AddressingMode::Implied)),
        0x29 => Some((Mnemonic::AND, AddressingMode::Immediate)),
        0x2a => Some((Mnemonic::ROL, AddressingMode::Accumulator)),
        0x2b => None,
        0x2c => Some((Mnemonic::BIT, AddressingMode::Absolute)),
        0x2d => Some((Mnemonic::AND, AddressingMode::Absolute)),
        0x2e => Some((Mnemonic::ROL, AddressingMode::Absolute)),
        0x2f => Some((Mnemonic::RLA, AddressingMode::Absolute)),
        0x30 => Some((Mnemonic::BMI, AddressingMode::Relative)),
        0x31 => Some((Mnemonic::AND, AddressingMode::IndirectY)),
        0x32 => None,
        0x33 => Some((Mnemonic::RLA, AddressingMode::IndirectY)),
        0x34 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPageX)),
        0x35 => Some((Mnemonic::AND, AddressingMode::ZeroPageX)),
        0x36 => Some((Mnemonic::ROL, AddressingMode::ZeroPageX)),
        0x37 => Some((Mnemonic::RLA, AddressingMode::ZeroPageX)),
        0x38 => Some((Mnemonic::SEC, AddressingMode::Implied)),
        0x39 => Some((Mnemonic::AND, AddressingMode::AbsoluteY)),
        0x3a => Some((Mnemonic::UndocumentedNOP, AddressingMode::Implied)),
        0x3b => Some((Mnemonic::RLA, AddressingMode::AbsoluteY)),
        0x3c => Some((Mnemonic::UndocumentedNOP, AddressingMode::AbsoluteX)),
        0x3d => Some((Mnemonic::AND, AddressingMode::AbsoluteX)),
        0x3e => Some((Mnemonic::ROL, AddressingMode::AbsoluteX)),
        0x3f => Some((Mnemonic::RLA, AddressingMode::AbsoluteX)),
        0x40 => Some((Mnemonic::RTI, AddressingMode::Implied)),
        0x41 => Some((Mnemonic::EOR, AddressingMode::IndirectX)),
        0x42 => None,
        0x43 => Some((Mnemonic::SRE, AddressingMode::IndirectX)),
        0x44 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPage)),
        0x45 => Some((Mnemonic::EOR, AddressingMode::ZeroPage)),
        0x46 => Some((Mnemonic::LSR, AddressingMode::ZeroPage)),
        0x47 => Some((Mnemonic::SRE, AddressingMode::ZeroPage)),
        0x48 => Some((Mnemonic::PHA, AddressingMode::Implied)),
        0x49 => Some((Mnemonic::EOR, AddressingMode::Immediate)),
        0x4a => Some((Mnemonic::LSR, AddressingMode::Accumulator)),
        0x4b => None,
        0x4c => Some((Mnemonic::JMP, AddressingMode::Absolute)),
        0x4d => Some((Mnemonic::EOR, AddressingMode::Absolute)),
        0x4e => Some((Mnemonic::LSR, AddressingMode::Absolute)),
        0x4f => Some((Mnemonic::SRE, AddressingMode::Absolute)),
        0x50 => Some((Mnemonic::BVC, AddressingMode::Relative)),
        0x51 => Some((Mnemonic::EOR, AddressingMode::IndirectY)),
        0x52 => None,
        0x53 => Some((Mnemonic::SRE, AddressingMode::IndirectY)),
        0x54 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPageX)),
        0x55 => Some((Mnemonic::EOR, AddressingMode::ZeroPageX)),
        0x56 => Some((Mnemonic::LSR, AddressingMode::ZeroPageX)),
        0x57 => Some((Mnemonic::SRE, AddressingMode::ZeroPageX)),
        0x58 => Some((Mnemonic::CLI, AddressingMode::Implied)),
        0x59 => Some((Mnemonic::EOR, AddressingMode::AbsoluteY)),
        0x5A => Some((Mnemonic::UndocumentedNOP, AddressingMode::Implied)),
        0x5b => Some((Mnemonic::SRE, AddressingMode::AbsoluteY)),
        0x5c => Some((Mnemonic::UndocumentedNOP, AddressingMode::Absolute)),
        0x5d => Some((Mnemonic::EOR, AddressingMode::AbsoluteX)),
        0x5e => Some((Mnemonic::LSR, AddressingMode::AbsoluteX)),
        0x5f => Some((Mnemonic::SRE, AddressingMode::AbsoluteX)),
        0x60 => Some((Mnemonic::RTS, AddressingMode::Implied)),
        0x61 => Some((Mnemonic::ADC, AddressingMode::IndirectX)),
        0x62 => None,
        0x63 => Some((Mnemonic::RRA, AddressingMode::IndirectX)),
        0x64 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPage)),
        0x65 => Some((Mnemonic::ADC, AddressingMode::ZeroPage)),
        0x66 => Some((Mnemonic::ROR, AddressingMode::ZeroPage)),
        0x67 => Some((Mnemonic::RRA, AddressingMode::ZeroPage)),
        0x68 => Some((Mnemonic::PLA, AddressingMode::Implied)),
        0x69 => Some((Mnemonic::ADC, AddressingMode::Immediate)),
        0x6a => Some((Mnemonic::ROR, AddressingMode::Accumulator)),
        0x6b => None,
        0x6c => Some((Mnemonic::JMP, AddressingMode::Indirect)),
        0x6d => Some((Mnemonic::ADC, AddressingMode::Absolute)),
        0x6e => Some((Mnemonic::ROR, AddressingMode::Absolute)),
        0x6f => Some((Mnemonic::RRA, AddressingMode::Absolute)),
        0x70 => Some((Mnemonic::BVS, AddressingMode::Relative)),
        0x71 => Some((Mnemonic::ADC, AddressingMode::IndirectY)),
        0x72 => None,
        0x73 => Some((Mnemonic::RRA, AddressingMode::IndirectY)),
        0x74 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPageX)),
        0x75 => Some((Mnemonic::ADC, AddressingMode::ZeroPageX)),
        0x76 => Some((Mnemonic::ROR, AddressingMode::ZeroPageX)),
        0x77 => Some((Mnemonic::RRA, AddressingMode::ZeroPageX)),
        0x78 => Some((Mnemonic::SEI, AddressingMode::Implied)),
        0x79 => Some((Mnemonic::ADC, AddressingMode::AbsoluteY)),
        0x7A => Some((Mnemonic::UndocumentedNOP, AddressingMode::Implied)),
        0x7b => Some((Mnemonic::RRA, AddressingMode::AbsoluteY)),
        0x7c => Some((Mnemonic::UndocumentedNOP, AddressingMode::AbsoluteX)),
        0x7d => Some((Mnemonic::ADC, AddressingMode::AbsoluteX)),
        0x7e => Some((Mnemonic::ROR, AddressingMode::AbsoluteX)),
        0x7f => Some((Mnemonic::RRA, AddressingMode::AbsoluteX)),
        0x80 => Some((Mnemonic::UndocumentedNOP, AddressingMode::Immediate)),
        0x81 => Some((Mnemonic::STA, AddressingMode::IndirectX)),
        0x82 => Some((Mnemonic::UndocumentedNOP, AddressingMode::Immediate)),
        0x83 => Some((Mnemonic::SAX, AddressingMode::IndirectX)),
        0x84 => Some((Mnemonic::STY, AddressingMode::ZeroPage)),
        0x85 => Some((Mnemonic::STA, AddressingMode::ZeroPage)),
        0x86 => Some((Mnemonic::STX, AddressingMode::ZeroPage)),
        0x87 => Some((Mnemonic::SAX, AddressingMode::ZeroPage)),
        0x88 => Some((Mnemonic::DEY, AddressingMode::Implied)),
        0x89 => Some((Mnemonic::UndocumentedNOP, AddressingMode::Immediate)),
        0x8a => Some((Mnemonic::TXA, AddressingMode::Implied)),
        0x8b => None,
        0x8c => Some((Mnemonic::STY, AddressingMode::Absolute)),
        0x8d => Some((Mnemonic::STA, AddressingMode::Absolute)),
        0x8e => Some((Mnemonic::STX, AddressingMode::Absolute)),
        0x8f => Some((Mnemonic::SAX, AddressingMode::Absolute)),
        0x90 => Some((Mnemonic::BCC, AddressingMode::Relative)),
        0x91 => Some((Mnemonic::STA, AddressingMode::IndirectY)),
        0x92 => None,
        0x93 => None,
        0x94 => Some((Mnemonic::STY, AddressingMode::ZeroPageX)),
        0x95 => Some((Mnemonic::STA, AddressingMode::ZeroPageX)),
        0x96 => Some((Mnemonic::STX, AddressingMode::ZeroPageY)),
        0x97 => Some((Mnemonic::SAX, AddressingMode::ZeroPageY)),
        0x98 => Some((Mnemonic::TYA, AddressingMode::Implied)),
        0x99 => Some((Mnemonic::STA, AddressingMode::AbsoluteY)),
        0x9a => Some((Mnemonic::TXS, AddressingMode::Implied)),
        0x9b => None,
        0x9c => None,
        0x9d => Some((Mnemonic::STA, AddressingMode::AbsoluteX)),
        0x9e => None,
        0x9f => None,
        0xa0 => Some((Mnemonic::LDY, AddressingMode::Immediate)),
        0xa1 => Some((Mnemonic::LDA, AddressingMode::IndirectX)),
        0xa2 => Some((Mnemonic::LDX, AddressingMode::Immediate)),
        0xa3 => Some((Mnemonic::LAX, AddressingMode::IndirectX)),
        0xa4 => Some((Mnemonic::LDY, AddressingMode::ZeroPage)),
        0xa5 => Some((Mnemonic::LDA, AddressingMode::ZeroPage)),
        0xa6 => Some((Mnemonic::LDX, AddressingMode::ZeroPage)),
        0xa7 => Some((Mnemonic::LAX, AddressingMode::ZeroPage)),
        0xa8 => Some((Mnemonic::TAY, AddressingMode::Implied)),
        0xa9 => Some((Mnemonic::LDA, AddressingMode::Immediate)),
        0xaa => Some((Mnemonic::TAX, AddressingMode::Implied)),
        0xab => None,
        0xac => Some((Mnemonic::LDY, AddressingMode::Absolute)),
        0xad => Some((Mnemonic::LDA, AddressingMode::Absolute)),
        0xae => Some((Mnemonic::LDX, AddressingMode::Absolute)),
        0xaf => Some((Mnemonic::LAX, AddressingMode::Absolute)),
        0xb0 => Some((Mnemonic::BCS, AddressingMode::Relative)),
        0xb1 => Some((Mnemonic::LDA, AddressingMode::IndirectY)),
        0xb2 => None,
        0xb3 => Some((Mnemonic::LAX, AddressingMode::IndirectY)),
        0xb4 => Some((Mnemonic::LDY, AddressingMode::ZeroPageX)),
        0xb5 => Some((Mnemonic::LDA, AddressingMode::ZeroPageX)),
        0xb6 => Some((Mnemonic::LDX, AddressingMode::ZeroPageY)),
        0xb7 => Some((Mnemonic::LAX, AddressingMode::ZeroPageY)),
        0xb8 => Some((Mnemonic::CLV, AddressingMode::Implied)),
        0xb9 => Some((Mnemonic::LDA, AddressingMode::AbsoluteY)),
        0xba => Some((Mnemonic::TSX, AddressingMode::Implied)),
        0xbb => None,
        0xbc => Some((Mnemonic::LDY, AddressingMode::AbsoluteX)),
        0xbd => Some((Mnemonic::LDA, AddressingMode::AbsoluteX)),
        0xbe => Some((Mnemonic::LDX, AddressingMode::AbsoluteY)),
        0xbf => Some((Mnemonic::LAX, AddressingMode::AbsoluteY)),
        0xc0 => Some((Mnemonic::CPY, AddressingMode::Immediate)),
        0xc1 => Some((Mnemonic::CMP, AddressingMode::IndirectX)),
        0xc2 => Some((Mnemonic::UndocumentedNOP, AddressingMode::Immediate)),
        0xc3 => Some((Mnemonic::DCP, AddressingMode::IndirectX)),
        0xc4 => Some((Mnemonic::CPY, AddressingMode::ZeroPage)),
        0xc5 => Some((Mnemonic::CMP, AddressingMode::ZeroPage)),
        0xc6 => Some((Mnemonic::DEC, AddressingMode::ZeroPage)),
        0xc7 => Some((Mnemonic::DCP, AddressingMode::ZeroPage)),
        0xc8 => Some((Mnemonic::INY, AddressingMode::Implied)),
        0xc9 => Some((Mnemonic::CMP, AddressingMode::Immediate)),
        0xca => Some((Mnemonic::DEX, AddressingMode::Implied)),
        0xcb => None,
        0xcc => Some((Mnemonic::CPY, AddressingMode::Absolute)),
        0xcd => Some((Mnemonic::CMP, AddressingMode::Absolute)),
        0xce => Some((Mnemonic::DEC, AddressingMode::Absolute)),
        0xcf => Some((Mnemonic::DCP, AddressingMode::Absolute)),
        0xd0 => Some((Mnemonic::BNE, AddressingMode::Relative)),
        0xd1 => Some((Mnemonic::CMP, AddressingMode::IndirectY)),
        0xd2 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPageX)),
        0xd3 => Some((Mnemonic::DCP, AddressingMode::IndirectY)),
        0xd4 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPageX)),
        0xd5 => Some((Mnemonic::CMP, AddressingMode::ZeroPageX)),
        0xd6 => Some((Mnemonic::DEC, AddressingMode::ZeroPageX)),
        0xd7 => Some((Mnemonic::DCP, AddressingMode::ZeroPageX)),
        0xd8 => Some((Mnemonic::CLD, AddressingMode::Implied)),
        0xd9 => Some((Mnemonic::CMP, AddressingMode::AbsoluteY)),
        0xda => Some((Mnemonic::UndocumentedNOP, AddressingMode::Implied)),
        0xdb => Some((Mnemonic::DCP, AddressingMode::AbsoluteY)),
        0xdc => Some((Mnemonic::UndocumentedNOP, AddressingMode::AbsoluteX)),
        0xdd => Some((Mnemonic::CMP, AddressingMode::AbsoluteX)),
        0xde => Some((Mnemonic::DEC, AddressingMode::AbsoluteX)),
        0xdf => Some((Mnemonic::DCP, AddressingMode::AbsoluteX)),
        0xe0 => Some((Mnemonic::CPX, AddressingMode::Immediate)),
        0xe1 => Some((Mnemonic::SBC, AddressingMode::IndirectX)),
        0xe2 => Some((Mnemonic::UndocumentedNOP, AddressingMode::Immediate)),
        0xe3 => Some((Mnemonic::ISB, AddressingMode::IndirectX)),
        0xe4 => Some((Mnemonic::CPX, AddressingMode::ZeroPage)),
        0xe5 => Some((Mnemonic::SBC, AddressingMode::ZeroPage)),
        0xe6 => Some((Mnemonic::INC, AddressingMode::ZeroPage)),
        0xe7 => Some((Mnemonic::ISB, AddressingMode::ZeroPage)),
        0xe8 => Some((Mnemonic::INX, AddressingMode::Implied)),
        0xe9 => Some((Mnemonic::SBC, AddressingMode::Immediate)),
        0xea => Some((Mnemonic::NOP, AddressingMode::Implied)),
        0xeb => Some((Mnemonic::SBC, AddressingMode::Immediate)),
        0xec => Some((Mnemonic::CPX, AddressingMode::Absolute)),
        0xed => Some((Mnemonic::SBC, AddressingMode::Absolute)),
        0xee => Some((Mnemonic::INC, AddressingMode::Absolute)),
        0xef => Some((Mnemonic::ISB, AddressingMode::Absolute)),
        0xf0 => Some((Mnemonic::BEQ, AddressingMode::Relative)),
        0xf1 => Some((Mnemonic::SBC, AddressingMode::IndirectY)),
        0xf2 => None,
        0xf3 => Some((Mnemonic::ISB, AddressingMode::IndirectY)),
        0xf4 => Some((Mnemonic::UndocumentedNOP, AddressingMode::ZeroPageX)),
        0xf5 => Some((Mnemonic::SBC, AddressingMode::ZeroPageX)),
        0xf6 => Some((Mnemonic::INC, AddressingMode::ZeroPageX)),
        0xf7 => Some((Mnemonic::ISB, AddressingMode::ZeroPageX)),
        0xf8 => Some((Mnemonic::SED, AddressingMode::Implied)),
        0xf9 => Some((Mnemonic::SBC, AddressingMode::AbsoluteY)),
        0xfa => Some((Mnemonic::UndocumentedNOP, AddressingMode::Implied)),
        0xfb => Some((Mnemonic::ISB, AddressingMode::AbsoluteY)),
        0xfc => Some((Mnemonic::UndocumentedNOP, AddressingMode::AbsoluteX)),
        0xfd => Some((Mnemonic::SBC, AddressingMode::AbsoluteX)),
        0xfe => Some((Mnemonic::INC, AddressingMode::AbsoluteX)),
        0xff => Some((Mnemonic::ISB, AddressingMode::AbsoluteX)),
        _ => None,
    }
}
pub static OPCODES_STRING: [&str; 256] = [
    " BRK 7        $00: bytes: 0 cycles: 0 _____=>_____ __ ",
    " ORA izx 6    $01: bytes: 2 cycles: 6 A____=>____P R_ izx",
    " *KIL         $02: CRASH",
    " *SLO izx 8   $03: bytes: 2 cycles: 8 A____=>____P RW izx",
    " *NOP zp 3    $04: bytes: 2 cycles: 3 _____=>_____ R_ zp",
    " ORA zp 3     $05: bytes: 2 cycles: 3 A____=>A___P R_ zp",
    " ASL zp 5     $06: bytes: 2 cycles: 5 _____=>____P RW zp",
    " *SLO zp 5    $07: bytes: 2 cycles: 5 A____=>A___P RW zp",
    " PHP 3        $08: bytes: 1 cycles: 3 ___SP=>___S_ _W ",
    " ORA imm 2    $09: bytes: 2 cycles: 2 _____=>A___P __ ",
    " ASL 2        $0A: bytes: 1 cycles: 2 A____=>A___P __ ",
    " *ANC imm 2   $0B: bytes: 2 cycles: 2 A____=>____P __ ",
    " *NOP abs 4   $0C: bytes: 3 cycles: 4 _____=>_____ R_ abs",
    " ORA abs 4    $0D: bytes: 3 cycles: 4 A____=>A___P R_ abs",
    " ASL abs 6    $0E: bytes: 3 cycles: 6 _____=>____P RW abs",
    " *SLO abs 6   $0F: bytes: 3 cycles: 6 A____=>A___P RW abs",
    " BPL rel 2*   $10: bytes: 2 cycles: 3 ____P=>_____ __ ",
    " ORA izy 5*   $11: bytes: 2 cycles: 5 A____=>____P R_ izy",
    " *KIL         $12: CRASH",
    " *SLO izy 8   $13: bytes: 2 cycles: 8 A____=>____P RW izy",
    " *NOP zpx 4   $14: bytes: 2 cycles: 4 _____=>_____ R_ zpx",
    " ORA zpx 4    $15: bytes: 2 cycles: 4 A____=>A___P R_ zpx",
    " ASL zpx 6    $16: bytes: 2 cycles: 6 _____=>____P RW zpx",
    " *SLO zpx 6   $17: bytes: 2 cycles: 6 A____=>A___P RW zpx",
    " CLC 2        $18: bytes: 1 cycles: 2 _____=>____P __ ",
    " ORA aby 4*   $19: bytes: 3 cycles: 4 A____=>A___P R_ absy",
    " *NOP 2       $1A: bytes: 1 cycles: 2 _____=>_____ __ ",
    " *SLO aby 7   $1B: bytes: 3 cycles: 7 A____=>A___P RW absy",
    " *NOP abx 4*  $1C: bytes: 3 cycles: 4 _____=>_____ R_ absx",
    " ORA abx 4*   $1D: bytes: 3 cycles: 4 A____=>A___P R_ absx",
    " ASL abx 7    $1E: bytes: 3 cycles: 7 _____=>____P RW absx",
    " *SLO abx 7   $1F: bytes: 3 cycles: 7 A____=>A___P RW absx",
    " JSR abs 6    $20: bytes: X cycles: 6 ___S_=>___S_ _W ",
    " AND izx 6    $21: bytes: 2 cycles: 6 _____=>A___P R_ izx",
    " *KIL         $22: CRASH",
    " *RLA izx 8   $23: bytes: 2 cycles: 8 ____P=>A___P RW izx",
    " BIT zp 3     $24: bytes: 2 cycles: 3 A____=>____P R_ zp",
    " AND zp 3     $25: bytes: 2 cycles: 3 A____=>A___P R_ zp",
    " ROL zp 5     $26: bytes: 2 cycles: 5 ____P=>____P RW zp",
    " *RLA zp 5    $27: bytes: 2 cycles: 5 A___P=>A___P RW zp",
    " PLP 4        $28: bytes: 1 cycles: 4 ___S_=>___SP __ ",
    " AND imm 2    $29: bytes: 2 cycles: 2 A____=>A___P __ ",
    " ROL 2        $2A: bytes: 1 cycles: 2 A___P=>A___P __ ",
    " *ANC imm 2   $2B: bytes: 2 cycles: 2 A____=>____P __ ",
    " BIT abs 4    $2C: bytes: 3 cycles: 4 A____=>____P R_ abs",
    " AND abs 4    $2D: bytes: 3 cycles: 4 A____=>A___P R_ abs",
    " ROL abs 6    $2E: bytes: 3 cycles: 6 ____P=>____P RW abs",
    " *RLA abs 6   $2F: bytes: 3 cycles: 6 A___P=>A___P RW abs",
    " BMI rel 2*   $30: bytes: 2 cycles: 2 _____=>_____ __ ",
    " AND izy 5*   $31: bytes: 2 cycles: 5 _____=>A___P R_ izy",
    " *KIL         $32: CRASH",
    " *RLA izy 8   $33: bytes: 2 cycles: 8 ____P=>A___P RW izy",
    " *NOP zpx 4   $34: bytes: 2 cycles: 4 _____=>_____ R_ zpx",
    " AND zpx 4    $35: bytes: 2 cycles: 4 A____=>A___P R_ zpx",
    " ROL zpx 6    $36: bytes: 2 cycles: 6 ____P=>____P RW zpx",
    " *RLA zpx 6   $37: bytes: 2 cycles: 6 A___P=>A___P RW zpx",
    " SEC 2        $38: bytes: 1 cycles: 2 _____=>____P __ ",
    " AND aby 4*   $39: bytes: 3 cycles: 4 A____=>A___P R_ absy",
    " *NOP 2       $3A: bytes: 1 cycles: 2 _____=>_____ __ ",
    " *RLA aby 7   $3B: bytes: 3 cycles: 7 A___P=>A___P RW absy",
    " *NOP abx 4*  $3C: bytes: 3 cycles: 4 _____=>_____ R_ absx",
    " AND abx 4*   $3D: bytes: 3 cycles: 4 A____=>A___P R_ absx",
    " ROL abx 7    $3E: bytes: 3 cycles: 7 ____P=>____P RW absx",
    " *RLA abx 7   $3F: bytes: 3 cycles: 7 A___P=>A___P RW absx",
    " RTI 6        $40: bytes: X cycles: 6 ___S_=>___SP __ ",
    " EOR izx 6    $41: bytes: 2 cycles: 6 A____=>____P R_ izx",
    " *KIL         $42: CRASH",
    " *SRE izx 8   $43: bytes: 2 cycles: 8 A____=>____P RW izx",
    " *NOP zp 3    $44: bytes: 2 cycles: 3 _____=>_____ R_ zp",
    " EOR zp 3     $45: bytes: 2 cycles: 3 A____=>A___P R_ zp",
    " LSR zp 5     $46: bytes: 2 cycles: 5 _____=>____P RW zp",
    " *SRE zp 5    $47: bytes: 2 cycles: 5 A____=>A___P RW zp",
    " PHA 3        $48: bytes: 1 cycles: 3 A__S_=>___S_ _W ",
    " EOR imm 2    $49: bytes: 2 cycles: 2 A____=>A___P __ ",
    " LSR 2        $4A: bytes: 1 cycles: 2 A____=>A___P __ ",
    " *ALR imm 2   $4B: bytes: 2 cycles: 2 A____=>A___P __ ",
    " JMP abs 3    $4C: bytes: X cycles: 3 _____=>_____ __ ",
    " EOR abs 4    $4D: bytes: 3 cycles: 4 A____=>A___P R_ abs",
    " LSR abs 6    $4E: bytes: 3 cycles: 6 _____=>____P RW abs",
    " *SRE abs 6   $4F: bytes: 3 cycles: 6 A____=>A___P RW abs",
    " BVC rel 2*   $50: bytes: 2 cycles: 3 ____P=>_____ __ ",
    " EOR izy 5*   $51: bytes: 2 cycles: 5 A____=>____P R_ izy",
    " *KIL         $52: CRASH",
    " *SRE izy 8   $53: bytes: 2 cycles: 8 A____=>____P RW izy",
    " *NOP zpx 4   $54: bytes: 2 cycles: 4 _____=>_____ R_ zpx",
    " EOR zpx 4    $55: bytes: 2 cycles: 4 A____=>A___P R_ zpx",
    " LSR zpx 6    $56: bytes: 2 cycles: 6 _____=>____P RW zpx",
    " *SRE zpx 6   $57: bytes: 2 cycles: 6 A____=>A___P RW zpx",
    " CLI 2        $58: bytes: 1 cycles: 2 _____=>____P __ ",
    " EOR aby 4*   $59: bytes: 3 cycles: 4 A____=>A___P R_ absy",
    " *NOP 2       $5A: bytes: 1 cycles: 2 _____=>_____ __ ",
    " *SRE aby 7   $5B: bytes: 3 cycles: 7 A____=>A___P RW absy",
    " *NOP abx 4*  $5C: bytes: 3 cycles: 4 _____=>_____ R_ absx",
    " EOR abx 4*   $5D: bytes: 3 cycles: 4 A____=>A___P R_ absx",
    " LSR abx 7    $5E: bytes: 3 cycles: 7 _____=>____P RW absx",
    " *SRE abx 7   $5F: bytes: 3 cycles: 7 A____=>A___P RW absx",
    " RTS 6        $60: bytes: X cycles: 6 ___S_=>___S_ __ ",
    " ADC izx 6    $61: bytes: 2 cycles: 6 A___P=>A___P R_ izx",
    " *KIL         $62: CRASH",
    " *RRA izx 8   $63: bytes: 2 cycles: 8 A___P=>A___P RW izx",
    " *NOP zp 3    $64: bytes: 2 cycles: 3 _____=>_____ R_ zp",
    " ADC zp 3     $65: bytes: 2 cycles: 3 A___P=>A___P R_ zp",
    " ROR zp 5     $66: bytes: 2 cycles: 5 ____P=>____P RW zp",
    " *RRA zp 5    $67: bytes: 2 cycles: 5 A___P=>A___P RW zp",
    " PLA 4        $68: bytes: 1 cycles: 4 ___S_=>A__SP __ ",
    " ADC imm 2    $69: bytes: 2 cycles: 2 A___P=>A___P __ ",
    " ROR 2        $6A: bytes: 1 cycles: 2 A___P=>A___P __ ",
    " *ARR imm 2   $6B: bytes: 2 cycles: 2 A___P=>A___P __ ",
    " JMP ind 5    $6C: bytes: X cycles: 5 _____=>_____ __ ",
    " ADC abs 4    $6D: bytes: 3 cycles: 4 A___P=>A___P R_ abs",
    " ROR abs 6    $6E: bytes: 3 cycles: 6 ____P=>____P RW abs",
    " *RRA abs 6   $6F: bytes: 3 cycles: 6 A___P=>A___P RW abs",
    " BVS rel 2*   $70: bytes: 2 cycles: 2 _____=>_____ __ ",
    " ADC izy 5*   $71: bytes: 2 cycles: 5 A___P=>A___P R_ izy",
    " *KIL         $72: CRASH",
    " *RRA izy 8   $73: bytes: 2 cycles: 8 A___P=>A___P RW izy",
    " *NOP zpx 4   $74: bytes: 2 cycles: 4 _____=>_____ R_ zpx",
    " ADC zpx 4    $75: bytes: 2 cycles: 4 A___P=>A___P R_ zpx",
    " ROR zpx 6    $76: bytes: 2 cycles: 6 ____P=>____P RW zpx",
    " *RRA zpx 6   $77: bytes: 2 cycles: 6 A___P=>A___P RW zpx",
    " SEI 2        $78: bytes: 1 cycles: 2 _____=>____P __ ",
    " ADC aby 4*   $79: bytes: 3 cycles: 4 A___P=>A___P R_ absy",
    " *NOP 2       $7A: bytes: 1 cycles: 2 _____=>_____ __ ",
    " *RRA aby 7   $7B: bytes: 3 cycles: 7 A___P=>A___P RW absy",
    " *NOP abx 4*  $7C: bytes: 3 cycles: 4 _____=>_____ R_ absx",
    " ADC abx 4*   $7D: bytes: 3 cycles: 4 A___P=>A___P R_ absx",
    " ROR abx 7    $7E: bytes: 3 cycles: 7 ____P=>____P RW absx",
    " *RRA abx 7   $7F: bytes: 3 cycles: 7 A___P=>A___P RW absx",
    " *NOP imm 2   $80: bytes: 2 cycles: 2 _____=>_____ __ ",
    " STA izx 6    $81: bytes: 2 cycles: 6 A____=>_____ RW izx",
    " *NOP imm 2   $82: bytes: 2 cycles: 2 _____=>_____ __ ",
    " *SAX izx 6   $83: bytes: 2 cycles: 6 _____=>_____ RW izx",
    " STY zp 3     $84: bytes: 2 cycles: 3 __Y__=>_____ _W zp",
    " STA zp 3     $85: bytes: 2 cycles: 3 A____=>_____ _W zp",
    " STX zp 3     $86: bytes: 2 cycles: 3 _X___=>_____ _W zp",
    " *SAX zp 3    $87: bytes: 2 cycles: 3 _____=>_____ _W zp",
    " DEY 2        $88: bytes: 1 cycles: 2 __Y__=>__Y_P __ ",
    " *NOP imm 2   $89: bytes: 2 cycles: 2 _____=>_____ __ ",
    " TXA 2        $8A: bytes: 1 cycles: 2 _X___=>A___P __ ",
    " *XAA imm 2   $8B: bytes: 2 cycles: 2 _____=>A___P __ ",
    " STY abs 4    $8C: bytes: 3 cycles: 4 __Y__=>_____ _W abs",
    " STA abs 4    $8D: bytes: 3 cycles: 4 A____=>_____ _W abs",
    " STX abs 4    $8E: bytes: 3 cycles: 4 _X___=>_____ _W abs",
    " *SAX abs 4   $8F: bytes: 3 cycles: 4 _____=>_____ _W abs",
    " BCC rel 2*   $90: bytes: 2 cycles: 3 ____P=>_____ __ ",
    " STA izy 6    $91: bytes: 2 cycles: 6 A____=>_____ RW izy",
    " *KIL         $92: CRASH",
    " *AHX izy 6   $93: bytes: 2 cycles: 6 _____=>_____ RW izy",
    " STY zpx 4    $94: bytes: 2 cycles: 4 __Y__=>_____ RW zpx",
    " STA zpx 4    $95: bytes: 2 cycles: 4 A____=>_____ RW zpx",
    " STX zpy 4    $96: bytes: 2 cycles: 4 _X___=>_____ RW zpy",
    " *SAX zpy 4   $97: bytes: 2 cycles: 4 _____=>_____ RW zpy",
    " TYA 2        $98: bytes: 1 cycles: 2 __Y__=>A___P __ ",
    " STA aby 5    $99: bytes: 3 cycles: 5 A____=>_____ RW absy",
    " TXS 2        $9A: bytes: X cycles: 2 _X___=>___S_ __ ",
    " *TAS aby 5   $9B: bytes: X cycles: 5 __Y__=>___S_ _W ",
    " *SHY abx 5   $9C: bytes: 3 cycles: 5 __Y__=>_____ RW absx",
    " STA abx 5    $9D: bytes: 3 cycles: 5 A____=>_____ RW absx",
    " *SHX aby 5   $9E: bytes: 3 cycles: 5 _X___=>_____ RW absy",
    " *AHX aby 5   $9F: bytes: 3 cycles: 5 _____=>_____ RW absy",
    " LDY imm 2    $A0: bytes: 2 cycles: 2 _____=>__Y_P __ ",
    " LDA izx 6    $A1: bytes: 2 cycles: 6 _____=>A___P R_ izx",
    " LDX imm 2    $A2: bytes: 2 cycles: 2 _____=>_X__P __ ",
    " *LAX izx 6   $A3: bytes: 2 cycles: 6 _____=>AX__P R_ izx",
    " LDY zp 3     $A4: bytes: 2 cycles: 3 _____=>__Y_P R_ zp",
    " LDA zp 3     $A5: bytes: 2 cycles: 3 _____=>A___P R_ zp",
    " LDX zp 3     $A6: bytes: 2 cycles: 3 _____=>_X__P R_ zp",
    " *LAX zp 3    $A7: bytes: 2 cycles: 3 _____=>AX__P R_ zp",
    " TAY 2        $A8: bytes: 1 cycles: 2 A____=>__Y_P __ ",
    " LDA imm 2    $A9: bytes: 2 cycles: 2 _____=>A___P __ ",
    " TAX 2        $AA: bytes: 1 cycles: 2 A____=>_X__P __ ",
    " *LAX imm 2   $AB: bytes: 2 cycles: 2 A____=>AX__P __ ",
    " LDY abs 4    $AC: bytes: 3 cycles: 4 _____=>__Y_P R_ abs",
    " LDA abs 4    $AD: bytes: 3 cycles: 4 _____=>A___P R_ abs",
    " LDX abs 4    $AE: bytes: 3 cycles: 4 _____=>_X__P R_ abs",
    " *LAX abs 4   $AF: bytes: 3 cycles: 4 _____=>AX__P R_ abs",
    " BCS rel 2*   $B0: bytes: 2 cycles: 2 _____=>_____ __ ",
    " LDA izy 5*   $B1: bytes: 2 cycles: 5 _____=>A___P R_ izy",
    " *KIL         $B2: CRASH",
    " *LAX izy 5*  $B3: bytes: 2 cycles: 5 _____=>AX__P R_ izy",
    " LDY zpx 4    $B4: bytes: 2 cycles: 4 _____=>__Y_P R_ zpx",
    " LDA zpx 4    $B5: bytes: 2 cycles: 4 _____=>A___P R_ zpx",
    " LDX zpy 4    $B6: bytes: 2 cycles: 4 _____=>_X__P R_ zpy",
    " *LAX zpy 4   $B7: bytes: 2 cycles: 4 _____=>AX__P R_ zpy",
    " CLV 2        $B8: bytes: 1 cycles: 2 _____=>____P __ ",
    " LDA aby 4*   $B9: bytes: 3 cycles: 4 _____=>A___P R_ absy",
    " TSX 2        $BA: bytes: 1 cycles: 2 ___S_=>_X__P __ ",
    " *LAS aby 4*  $BB: bytes: 3 cycles: 4 ___S_=>AX_SP R_ absy",
    " LDY abx 4*   $BC: bytes: 3 cycles: 4 _____=>__Y_P R_ absx",
    " LDA abx 4*   $BD: bytes: 3 cycles: 4 _____=>A___P R_ absx",
    " LDX aby 4*   $BE: bytes: 3 cycles: 4 _____=>_X__P R_ absy",
    " *LAX aby 4*  $BF: bytes: 3 cycles: 4 _____=>AX__P R_ absy",
    " CPY imm 2    $C0: bytes: 2 cycles: 2 __Y__=>____P __ ",
    " CMP izx 6    $C1: bytes: 2 cycles: 6 A____=>____P R_ izx",
    " *NOP imm 2   $C2: bytes: 2 cycles: 2 _____=>_____ __ ",
    " *DCP izx 8   $C3: bytes: 2 cycles: 8 A____=>____P RW izx",
    " CPY zp 3     $C4: bytes: 2 cycles: 3 __Y__=>____P R_ zp",
    " CMP zp 3     $C5: bytes: 2 cycles: 3 A____=>____P R_ zp",
    " DEC zp 5     $C6: bytes: 2 cycles: 5 _____=>____P RW zp",
    " *DCP zp 5    $C7: bytes: 2 cycles: 5 A____=>____P RW zp",
    " INY 2        $C8: bytes: 1 cycles: 2 __Y__=>__Y_P __ ",
    " CMP imm 2    $C9: bytes: 2 cycles: 2 A____=>____P __ ",
    " DEX 2        $CA: bytes: 1 cycles: 2 _X___=>_X__P __ ",
    " *AXS imm 2   $CB: bytes: 2 cycles: 2 _____=>_X__P __ ",
    " CPY abs 4    $CC: bytes: 3 cycles: 4 __Y__=>____P R_ abs",
    " CMP abs 4    $CD: bytes: 3 cycles: 4 A____=>____P R_ abs",
    " DEC abs 6    $CE: bytes: 3 cycles: 6 _____=>____P RW abs",
    " *DCP abs 6   $CF: bytes: 3 cycles: 6 A____=>____P RW abs",
    " BNE rel 2*   $D0: bytes: 2 cycles: 3 ____P=>_____ __ ",
    " CMP izy 5*   $D1: bytes: 2 cycles: 5 A____=>____P R_ izy",
    " *KIL         $D2: CRASH",
    " *DCP izy 8   $D3: bytes: 2 cycles: 8 A____=>____P RW izy",
    " *NOP zpx 4   $D4: bytes: 2 cycles: 4 _____=>_____ R_ zpx",
    " CMP zpx 4    $D5: bytes: 2 cycles: 4 A____=>____P R_ zpx",
    " DEC zpx 6    $D6: bytes: 2 cycles: 6 _____=>____P RW zpx",
    " *DCP zpx 6   $D7: bytes: 2 cycles: 6 A____=>____P RW zpx",
    " CLD 2        $D8: bytes: 1 cycles: 2 _____=>____P __ ",
    " CMP aby 4*   $D9: bytes: 3 cycles: 4 A____=>____P R_ absy",
    " *NOP 2       $DA: bytes: 1 cycles: 2 _____=>_____ __ ",
    " *DCP aby 7   $DB: bytes: 3 cycles: 7 A____=>____P RW absy",
    " *NOP abx 4*  $DC: bytes: 3 cycles: 4 _____=>_____ R_ absx",
    " CMP abx 4*   $DD: bytes: 3 cycles: 4 A____=>____P R_ absx",
    " DEC abx 7    $DE: bytes: 3 cycles: 7 _____=>____P RW absx",
    " *DCP abx 7   $DF: bytes: 3 cycles: 7 A____=>____P RW absx",
    " CPX imm 2    $E0: bytes: 2 cycles: 2 _X___=>____P __ ",
    " SBC izx 6    $E1: bytes: 2 cycles: 6 A___P=>A___P R_ izx",
    " *NOP imm 2   $E2: bytes: 2 cycles: 2 _____=>_____ __ ",
    " *ISC izx 8   $E3: bytes: 2 cycles: 8 A___P=>A___P RW izx",
    " CPX zp 3     $E4: bytes: 2 cycles: 3 _X___=>____P R_ zp",
    " SBC zp 3     $E5: bytes: 2 cycles: 3 A___P=>A___P R_ zp",
    " INC zp 5     $E6: bytes: 2 cycles: 5 _____=>____P RW zp",
    " *ISC zp 5    $E7: bytes: 2 cycles: 5 A___P=>A___P RW zp",
    " INX 2        $E8: bytes: 1 cycles: 2 _X___=>_X__P __ ",
    " SBC imm 2    $E9: bytes: 2 cycles: 2 A___P=>A___P __ ",
    " NOP 2        $EA: bytes: 1 cycles: 2 _____=>_____ __ ",
    " *SBC imm 2   $EB: bytes: 2 cycles: 2 A___P=>A___P __ ",
    " CPX abs 4    $EC: bytes: 3 cycles: 4 _X___=>____P R_ abs",
    " SBC abs 4    $ED: bytes: 3 cycles: 4 A___P=>A___P R_ abs",
    " INC abs 6    $EE: bytes: 3 cycles: 6 _____=>____P RW abs",
    " *ISC abs 6   $EF: bytes: 3 cycles: 6 A___P=>A___P RW abs",
    " BEQ rel 2*   $F0: bytes: 2 cycles: 2 _____=>_____ __ ",
    " SBC izy 5*   $F1: bytes: 2 cycles: 5 A___P=>A___P R_ izy",
    " *KIL         $F2: CRASH",
    " *ISC izy 8   $F3: bytes: 2 cycles: 8 A___P=>A___P RW izy",
    " *NOP zpx 4   $F4: bytes: 2 cycles: 4 _____=>_____ R_ zpx",
    " SBC zpx 4    $F5: bytes: 2 cycles: 4 A___P=>A___P R_ zpx",
    " INC zpx 6    $F6: bytes: 2 cycles: 6 _____=>____P RW zpx",
    " *ISC zpx 6   $F7: bytes: 2 cycles: 6 A___P=>A___P RW zpx",
    " SED 2        $F8: bytes: 1 cycles: 2 _____=>____P __ ",
    " SBC aby 4*   $F9: bytes: 3 cycles: 4 A___P=>A___P R_ absy",
    " *NOP 2       $FA: bytes: 1 cycles: 2 _____=>_____ __ ",
    " *ISC aby 7   $FB: bytes: 3 cycles: 7 A___P=>A___P RW absy",
    " *NOP abx 4*  $FC: bytes: 3 cycles: 4 _____=>_____ R_ absx",
    " SBC abx 4*   $FD: bytes: 3 cycles: 4 A___P=>A___P R_ absx",
    " INC abx 7    $FE: bytes: 3 cycles: 7 _____=>____P RW absx",
    " *ISC abx     $FF: bytes: 3 cycles: 7 A___P=>A___P RW absx",
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Mnemonic {
    ADC,
    AND,
    ASL,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    JMP,
    JSR,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    ROL,
    ROR,
    RTI,
    RTS,
    SBC,
    SEC,
    SED,
    SEI,
    STA,
    STX,
    STY,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
    //unofficial but require for full emulation 
    UndocumentedNOP,
    LAX,    
    SAX,
    DCP,
    ISB,
    SLO,
    RLA,
    SRE,
    RRA
}
