[package]
name = "nes_core"
version = "0.1.0"
edition = "2021"
description = "A core library for a NES emulator, handling CPU, PPU, and memory."

[dependencies]
[dependencies.bitflags]
version = "2.9.0"